name: 'Pull Request Review Notify'
description: 'Get started with Node actions'
author: 'GitHub'
inputs:
  platform:
    description: 'target platform'
    default: 'slack'
  message:
    description: 'message to send'
  webhook:
    description: 'webhook URL'
  debug:
    description: 'Enable debug output - *MUST* also set secret ACTIONS_STEP_DEBUG to "true"'
    default: false
runs:
  using: 'node12'
  main: 'lib/main.js'
