name: 'Pull Request Review Notify'
description: 'Get started with Node actions'
author: 'GitHub'
inputs:
  platform:
    description: 'Platform to notify'
    default: 'Slack'
  message:
    description: 'Message to send suffixed with PR link'
    default: 'This pull request is approved and ready to merge: '
  webhook:
    description: 'URL or webhook to send the message to'
runs:
  using: 'node12'
  main: 'lib/main.js'
